function Plot(N)
% Plot(N)
%   Plot generates N start and goal locations and plots the trajectories
%   generated by CaptBasic
    

while 1 == 1
    start = rand(N, 2).*5;
    goal = rand(N, 2).*5;
    
    
    try
        traj = DCapt(start, goal, 0.2, 0.6);
        
        break;
    catch e
    end
       
end

init(start, goal, traj);



h = uicontrol('style','slider','units','pixel','position',[140 10 300 20]);

addlistener(h,'ContinuousValueChange',@(hObject, event) DrawCurrent(hObject, start, goal, traj));
end



