function Plot(N)
% Plot(N)
%   Plot generates N start and goal locations and plots the trajectories
%   generated by CaptBasic

start = randn(N, 2).*10;
goal = randn(N, 2).*10;
try
  [traj, unassigned_goals] = CaptBasic(start, goal, 0.5);
catch e
end

init(start, goal, traj);
h = uicontrol('style','slider','units','pixel','position',[140 10 300 20]);
addlistener(h,'ContinuousValueChange',@(hObject, event) DrawCurrent(hObject, start, goal, traj));

distMat = pdist2(start,start);
Z = linkage(distMat);
I = inconsistent(Z);
T = cluster(Z,'cutoff',25,'criterion','distance');

%figure, dendrogram(Z)

figure,scatter(start(:,1), start(:,2), 100, T,'filled')

num_clusters = max(T);

unassigned_goals = goal;
traj_list.desPos = {};
traj_list.time=[];
for i = 1: num_clusters
  cluster_start = start(T==i,:);
  try
    [traj, unassigned_goals] = CaptBasic(cluster_start, unassigned_goals, 0.5);
    for j = 1:size(traj.desPos,2)
      traj_list.desPos(end+1) = traj.desPos(j);
      traj_list.time=traj.time;
    end
  catch e
  end
end

figure;
init(start, goal, traj_list);
h2 = uicontrol('style','slider','units','pixel','position',[140 10 300 20]);
addlistener(h2,'ContinuousValueChange',@(hObject, event) DrawCurrent(hObject, start, goal, traj_list));

end



