function Plot_capt(N)
% Plot_capt(N)
%   Plot generates N start and goal locations and plots the trajectories
%   generated by CaptBasic

start = randn(N, 2).*10;
goal = randn(N, 2).*10;

[traj, unassigned_goals] = CaptBasic(start, goal, 0.5);

init(start, goal, traj);
h = uicontrol('style','slider','units','pixel','position',[140 10 300 20]);
addlistener(h,'ContinuousValueChange',@(hObject, event) DrawCurrent(hObject, start, goal, traj));

end



